-- ============================================================================
-- 创建20个教学用设备
-- 文件: 23_create_teaching_devices.sql
-- 日期: 2025-11-27
-- 说明: 为教学活动预先注册20个设备，配置相同的传感器和预设指令
--       UUID使用MySQL内置UUID()函数自动生成
-- ============================================================================

-- 注意：
-- 1. 本脚本使用MySQL的UUID()函数自动生成设备UUID
-- 2. 执行后请查询数据库获取实际生成的UUID
-- 3. 将生成的UUID分配给学生使用

-- 查看生成的设备UUID：
-- SELECT name, uuid, device_id, mac_address FROM aiot_core_devices WHERE name LIKE '教学设备%' ORDER BY name;

INSERT INTO `aiot_core_devices` (
    `uuid`, `device_id`, `product_id`, `user_id`, `name`, `description`, 
    `device_secret`, `firmware_version`, `hardware_version`, `device_status`, 
    `is_online`, `is_active`, `mac_address`, 
    `device_sensor_config`, `device_control_config`, `device_settings`, 
    `quality_grade`, `error_count`, `uptime`, `product_switch_count`, `auto_created_product`,
    `created_at`, `updated_at`
) VALUES

-- 设备01
(UUID(), 'AIOT-ESP32-TEACH01', 2, 1, '教学设备01', '用于教学演示的设备', 
'teach01secret1234567890abcdef0001', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:01', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备02
(UUID(), 'AIOT-ESP32-TEACH02', 2, 1, '教学设备02', '用于教学演示的设备', 
'teach02secret1234567890abcdef0002', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:02', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备03
(UUID(), 'AIOT-ESP32-TEACH03', 2, 1, '教学设备03', '用于教学演示的设备', 
'teach03secret1234567890abcdef0003', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:03', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备04
(UUID(), 'AIOT-ESP32-TEACH04', 2, 1, '教学设备04', '用于教学演示的设备', 
'teach04secret1234567890abcdef0004', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:04', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备05
(UUID(), 'AIOT-ESP32-TEACH05', 2, 1, '教学设备05', '用于教学演示的设备', 
'teach05secret1234567890abcdef0005', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:05', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备06
(UUID(), 'AIOT-ESP32-TEACH06', 2, 1, '教学设备06', '用于教学演示的设备', 
'teach06secret1234567890abcdef0006', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:06', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备07
(UUID(), 'AIOT-ESP32-TEACH07', 2, 1, '教学设备07', '用于教学演示的设备', 
'teach07secret1234567890abcdef0007', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:07', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备08
(UUID(), 'AIOT-ESP32-TEACH08', 2, 1, '教学设备08', '用于教学演示的设备', 
'teach08secret1234567890abcdef0008', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:08', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备09
(UUID(), 'AIOT-ESP32-TEACH09', 2, 1, '教学设备09', '用于教学演示的设备', 
'teach09secret1234567890abcdef0009', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:09', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备10
(UUID(), 'AIOT-ESP32-TEACH10', 2, 1, '教学设备10', '用于教学演示的设备', 
'teach10secret1234567890abcdef0010', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:10', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备11
(UUID(), 'AIOT-ESP32-TEACH11', 2, 1, '教学设备11', '用于教学演示的设备', 
'teach11secret1234567890abcdef0011', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:11', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备12
(UUID(), 'AIOT-ESP32-TEACH12', 2, 1, '教学设备12', '用于教学演示的设备', 
'teach12secret1234567890abcdef0012', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:12', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备13
(UUID(), 'AIOT-ESP32-TEACH13', 2, 1, '教学设备13', '用于教学演示的设备', 
'teach13secret1234567890abcdef0013', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:13', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备14
(UUID(), 'AIOT-ESP32-TEACH14', 2, 1, '教学设备14', '用于教学演示的设备', 
'teach14secret1234567890abcdef0014', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:14', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备15
(UUID(), 'AIOT-ESP32-TEACH15', 2, 1, '教学设备15', '用于教学演示的设备', 
'teach15secret1234567890abcdef0015', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:15', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备16
(UUID(), 'AIOT-ESP32-TEACH16', 2, 1, '教学设备16', '用于教学演示的设备', 
'teach16secret1234567890abcdef0016', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:16', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备17
(UUID(), 'AIOT-ESP32-TEACH17', 2, 1, '教学设备17', '用于教学演示的设备', 
'teach17secret1234567890abcdef0017', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:17', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备18
(UUID(), 'AIOT-ESP32-TEACH18', 2, 1, '教学设备18', '用于教学演示的设备', 
'teach18secret1234567890abcdef0018', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:18', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备19
(UUID(), 'AIOT-ESP32-TEACH19', 2, 1, '教学设备19', '用于教学演示的设备', 
'teach19secret1234567890abcdef0019', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:19', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW()),

-- 设备20
(UUID(), 'AIOT-ESP32-TEACH20', 2, 1, '教学设备20', '用于教学演示的设备', 
'teach20secret1234567890abcdef0020', '1.5', 'ESP32', 'bound', 
0, 1, '80:B5:4E:D6:F8:20', 
'{\"DHT11_humidity\": {\"enabled\": true, \"custom_name\": \"\"}, \"DHT11_temperature\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"led_1\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_2\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_3\": {\"enabled\": true, \"custom_name\": \"\"}, \"led_4\": {\"enabled\": true, \"custom_name\": \"\"}}', 
'{\"preset_commands\": [{\"cmd\": \"sequence\", \"name\": \"LED1打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 1, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 1, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig4wqy5\", \"description\": \"序列预设：LED1打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED2打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 2, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 2, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5hiep\", \"description\": \"序列预设：LED2打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED3打开3秒关闭\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 3, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 3, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5i461\", \"description\": \"序列预设：LED3打开3秒关闭\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}, {\"cmd\": \"sequence\", \"name\": \"LED4打开3秒\", \"type\": \"sequence\", \"steps\": [{\"delay\": 3, \"command\": {\"cmd\": \"led\", \"value\": 1, \"device_id\": 4, \"device_type\": \"led\"}}, {\"delay\": 0, \"command\": {\"cmd\": \"led\", \"value\": 0, \"device_id\": 4, \"device_type\": \"led\"}}], \"preset_key\": \"led_seq_mig5ivu5\", \"description\": \"序列预设：LED4打开3秒\", \"device_type\": \"led\", \"preset_type\": \"sequence\"}]}', 
'A', 0, 0, 0, 0, NOW(), NOW());

-- ============================================================================
-- 验证和导出查询
-- ============================================================================

-- 1. 查看生成的设备UUID（执行插入后运行）
SELECT 
    SUBSTRING(name, 5) as '设备编号',
    uuid as 'UUID',
    device_id as 'Device ID',
    device_secret as 'Device Secret',
    mac_address as 'MAC地址'
FROM aiot_core_devices 
WHERE name LIKE '教学设备%' 
ORDER BY name;

-- 2. 导出为CSV格式（可复制结果）
SELECT 
    SUBSTRING(name, 5) as '设备编号',
    uuid,
    device_id,
    device_secret,
    mac_address
FROM aiot_core_devices 
WHERE name LIKE '教学设备%' 
ORDER BY name;

-- 3. 仅查看UUID列表（供学生使用）
SELECT 
    name as '设备名称',
    uuid as '设备UUID'
FROM aiot_core_devices 
WHERE name LIKE '教学设备%' 
ORDER BY name;

